### ISSUE TITLE
Progress for Series in Anime lists is gone

### ISSUE THREAD

**Issue by riggyz** [ValerioLyndon/MAL-Public-List-Designs#32]
The progress bar is gone in the newest two commits to the tilt theme. I have checked and it works in the mangalist but not the animelist. 418d223 is the one with the latest working for only anime.

**Comment by ValerioLyndon** [comment]
Very sorry for the late response, you're the first person to open an issue here!

Appreciate the bug report. Unfortunately, I can't seem to reproduce the issue you are having. It looks fine on my side in both Chrome and Firefox. What browser are you using? I'm curious, is it completely invisible and can you see the season and studio info still? A screenshot might be useful here.

![18-10-10 22-34-46 1081x256](https://user-images.githubusercontent.com/29792052/46782860-bd8ff600-ccdc-11e8-8476-eb5e03772b81.png)

**Comment by riggyz** [comment]
So this is what it looks like in 418d223: 
![screen shot 2018-10-11 at 10 47 42 am](https://user-images.githubusercontent.com/29961406/46812629-1befbf80-cd43-11e8-9810-ded6e5fd16b3.png)
And this is what it looks like in the new one: 
![screen shot 2018-10-11 at 10 55 11 am](https://user-images.githubusercontent.com/29961406/46813152-29f21000-cd44-11e8-9432-4e6d21496b86.png)

**Comment by riggyz** [comment]
So yeah, the option for watching and adding episodes is completely gone on mine, even when I hover over it or try to force it it does not work.

**Comment by ValerioLyndon** [comment]
Hm, the progress is supposed to be on the same line as everything else, even in the older versions. Are you sure you have all the list settings correctly set? If you have anything enabled that isn't enabled in this picture, you will need to uncheck those items:
![tilt options](https://user-images.githubusercontent.com/29792052/47261740-ea859b00-d48a-11e8-9c44-266f91a20038.png)

It looks to me like you might have "Type" checked when it shouldn't be, perhaps?

**Comment by riggyz** [comment]
That did the trick! By the way could I have the import statement because I kinda deleted it when I started to test this derp.

**Comment by ValerioLyndon** [comment]
Glad it's working now. The import statement is as such:
`@\import "https://valeriolyndon.github.io/MAL-Public-List-Designs/Tilt%20Theme/Theme%20-%20Compressed.css";`

And if you ever need to reinstall or revisit the instructions in the future, I have them on the [forum thread](https://myanimelist.net/forum/?topicid=1723118).
