### ISSUE TITLE
C| Score select box has issues on Firefox

### ISSUE THREAD

**Issue by ValerioLyndon** [ValerioLyndon/MAL-Public-List-Designs#39]
As seen here:
![19-04-03 (20-51-36) 57x44](https://user-images.githubusercontent.com/29792052/55530406-eaeda900-565a-11e9-8dc1-057ca990bf0f.png)
Possibly fixable, but Firefox form styling is a pain. If it isn't, then, oh well.

**Comment by GiacomoLaw** [comment]
Can you link to this in the CSS? I would be happy to take a look.

Also, love your theme: https://myanimelist.net/animelist/dipperdolphin

Looks great!

**Comment by ValerioLyndon** [comment]
@GiacomoLaw Should be fixed now, but thanks for the offer. :)
