### ISSUE TITLE
Broken profile picture

### ISSUE THREAD

**Issue by homuzx** [ValerioLyndon/MAL-Public-List-Designs#48]
Hi! You added a background: 0 0!important and the profile pic is not visible anymore.

The class is: 

[data-owner="1"] .list-menu-float .icon-menu.profile

You can watch the problem here:
https://myanimelist.net/animelist/PabloReviews

Thank you!

**Comment by ValerioLyndon** [comment]
Hey, sorry for the late response. People so rarely post here, so I'm not good at checking it. Are you still having this issue? If so, may I ask what browser you're using, what the profile area looks like to you, and what URL you are attempting to use for the profile picture? I can't reproduce the issue.

**Comment by homuzx** [comment]
Hi! Sorry for the late reply too. If you prefer to talk in some social network, just tell me!

The main problem is the one I said about the !important value in the background for the icon, that's why I can't see the image. Maybe I'm using a wrong version of them?

Asking your answers: I have the same problem with all browsers.

My profile area looks like: Score, Type, Episodes, Tags, Priority, Image, Premiered, Studios

And my custom CSS is:

@import "https://valeriolyndon.github.io/MAL-Public-List-Designs/Clarity%20Theme/Theme%20-%20Compressed.css";

@\import "https://malscraper.azurewebsites.net/covers/auto/presets/dataimagelinkbefore";

@\import "https://valeriolyndon.github.io/MAL-Public-List-Designs/Clarity%20Theme/Mod%20-%20Hover%20Image%20Compressed.css";


/* @import "https://valeriolyndon.github.io/MAL-Public-List-Designs/Clarity%20Theme/Mod%20-%20Dark%20Mode%20Compressed.css"; */

:root {
/* Imagen perfil */
    --avatar: url(https://pbs.twimg.com/profile_images/1162841538357092354/xbzK2XGQ_400x400.jpg);
/* Imagen banner */
    --banner: url(https://yt3.ggpht.com/KIkpnyh8Q5UyhDZwyxYCTHXYOgo6TtHoRZL6Cc7ukNI0i6EekhuWwzr1ORoozswzjf7NOq9KDg=w2560-fcrop64=1,00005a57ffffa5a8-k-c0xffffffff-no-nd-rj);
/* Generic Colours */
    --accent: #fd297e;
/* Button Colours */
    --btn-head-bg-h: #fd297e;
/* Header Colours */
    --text-head: #fd297e;
/* Status Colours */
    --watching: #2db039;
    --completed: #26448f;
    --onhold: #f9d457;
    --dropped: #a12f31;
    --plantowatch: #c3c3c3;
/* Single-Use Colours */
  	--cover-bg: #090909;
	  --edit-btn: #323232;
    --checkmark:#fd297e;
/* Fix */
  --character:none;
}

/* TAG COLORS */

.data.tags span a[href*="\=Lunes"] { font-weight: bold; color: #00FFBF !important }
.data.tags span a[href*="\=Martes"] { font-weight: bold; color: #FE9A2E !important }
.data.tags span a[href*="\=Miercoles"] { font-weight: bold; color: #31be00!important }
.data.tags span a[href*="\=Jueves"] { font-weight: bold; color: #FE2EF7 !important }
.data.tags span a[href*="\=Viernes"] { font-weight: bold; color: #F7FE2E !important }
.data.tags span a[href*="\=Sabado"] { font-weight: bold; color: #00BFFF !important }
.data.tags span a[href*="\=Domingo"] { font-weight: bold; color: #FE2E2E !important }
.data.tags span a[href*="\=No%20emision"] { font-weight: bold; color: #FFFFFF !important}

.data.tags span a[href*="\=CRUNCHYROLL"] { font-weight: bold; color: #ba2c7c !important }
.data.tags span a[href*="\=SELECTA%20VISION"] { font-weight: bold; color: #ba2c7c !important }

Thank you for helping me!^^

**Comment by homuzx** [comment]
Oh, I just solved it changing the image URL... So... Thank you! It was my fault at the end u.u

**Comment by ValerioLyndon** [comment]
No problem at all, I'm glad the issue was found. Some image URLs don't play nicely with CSS due to being invalid or the image hoster disabling such functionality. This can often be an issue with images found off of Google or the like, but rehosting the image usually solves such issues.
