### ISSUE TITLE
Tilt | Big preview pics (comment CSS on MAL page) don't work

### ISSUE THREAD

**Issue by VegethB** [ValerioLyndon/MAL-Public-List-Designs#53]
![image](https://user-images.githubusercontent.com/17975351/111081089-d8946f00-8501-11eb-8a50-8c5c92f33c44.png)

css:
```
@\import "https://valeriolyndon.github.io/MAL-Public-List-Designs/Tilt%20Theme/Theme%20-%20Compressed.css";
@\import "https://malscraper.azurewebsites.net/covers/auto/presets/dataimagelinkbefore";


/* COVER AREA
The area taken up by covers.
*/
.list-block {
/* variables used in calc (explicit names) */
--height-img: 250px !important;
--width-img: 178px !important;
}


/* HD COVER SIZE
The size of covers seen.
*/
.data.image a:before{
background-size: cover !important;
height: 250px !important;
width: 178px !important;
background-position: center center !important;
}


/* LOW RES COVER SIZE
You only see this if the import for high res covers goes down.
*/
a img{
background-size: cover !important;
height: 250px !important;
width: 178px !important;
}

/* OTHER CODES*/

.data.image .image{
display: inherit !important;
background-repeat: no-repeat !important;
}

a img{
display: block !important;
border: none !important;
background-repeat: no-repeat !important;
}

.data.image a:before{
display: block;
content: "";
position: absolute;
background-repeat: no-repeat !important;
}



.list-table-data {

width: 340px;
height: 250px;

}

.add-edit-more {

width: 180px;
height: 250px;}

.data.title .link.sort {

left: 110px;
}
```

Copy pasted CSS result:
![image](https://user-images.githubusercontent.com/17975351/111081129-15606600-8502-11eb-8073-ff6b37c3a1e8.png)

Either by adding this CSS to the base CSS, or by putting only this CSS in the box.
I don't understand if I have to replace something in the original CSS with this written in the comment or if this CSS was just a draft and then had to be adapted with firefox.

**Comment by ValerioLyndon** [comment]
Please note that that code is made by a third party and I don't take any credit for whether it works or not. That said, the covers work fine for me. You're probably using a privacy/ad-blocking browser extension/setting or your animelist is set to private/friends only. First things first, you need to delete this line:
```
@\import "https://malscraper.azurewebsites.net/covers/auto/presets/dataimagelinkbefore";
```

Next, use either of these fixes (not both).

To fix issues with privacy blockers add one or both of these lines at the top of your CSS (one will give anime covers, one gives manga covers). You'll need to replace the "USERNAME" text with your *exact* MyAnimeList username.
```
@\import "https://malscraper.azurewebsites.net/covers/anime/USERNAME/presets/dataimagelinkbefore";
@\import "https://malscraper.azurewebsites.net/covers/manga/USERNAME/presets/dataimagelinkbefore";
```

To fix covers on a private list or to solve any other issue, you'll need to use this alternate import. This one is inferior to the previous imports and may occasionally have missing or out of date covers for a few weeks here and there, so only use it if you need it. That said, it's the best option for private lists. Add one or both of these lines at the top of your CSS (one will give anime covers, one gives manga covers):
```
@\import "https://dl.dropboxusercontent.com/s/71mrsl1iz0z11p2/animelist_dataimagelinkbefore.css";
@\import "https://dl.dropboxusercontent.com/s/dpqglnr3slmgp7t/mangalist_dataimagelinkbefore.css";
```

If you ever need to fix high resolution cover images in the future, I have a [blog post](https://myanimelist.net/blog.php?eid=827400) which covers this topic and will be kept up-to-date with fixes. Alternatively you can find [this guide](https://myanimelist.net/forum/?topicid=439897) on fixing broken layouts in the same club as the forum topic you were looking at.

**Comment by VegethB** [comment]
> Please note that that code is made by a third party and I don't take any credit for whether it works or not.

Yes I had seen, but unfortunately it says that you must be a member of a club (I don't understand why...) to be able to write in the comments of the post. Thanks anyway.


> ou're probably using a privacy/ad-blocking browser extension/setting or your animelist is set to private/friends only.

Yes, I use Adblock and Tampermonkey, adblock is totally disabled for MAL (but maybe it blocks links inside the css even if it's paused when you open MAL), Tampermonkey I just disabled it (so it doesn't load any script). So I'd say they're not (definitely) giving me that problem.

The list is public (precisely because using it private / semi-private always gave problems)

I removed the `@\import "https://malscraper.azurewebsites.net/covers/auto/presets/dataimagelinkbefore";` and added, at the top, only the one for manga (as it will be used for manga).
The result is this: 
![image](https://user-images.githubusercontent.com/17975351/111145978-34eea180-8589-11eb-8bab-1eb34e9486e1.png)

which from how it looks, looks identical to the example screen on the comment. So the problem was due to that `@\import`.
Now, I don't know if the visualization of the old layout is buggy because I have to adapt it (in the comment we talked about using firefox and then copying the css edited in firefox instead of the old one or above) or if again I'm wrong on something.
Thank you again for the advice.

The reason for wanting this change is because I use small monitors (10", 6") and I find it difficult to scroll through the list to check it with such tiny posters and text. I had looked for alternative css themes but honestly everyone does... 
no one who puts all the minimum info (like on Anilist) next to/below... but inside, forcing you to get over it with the mouse to see the details.

**Comment by ValerioLyndon** [comment]
I think the code Shishio gave was more of a get-started kit than a polished modification to the theme. It is possible to make some changes to decrease the jank, but to prevent myself from having to recode a large section of the theme/design I kept it basic. Otherwise, we begin to enter custom to-request list territory. Here's a preview image and the code. This is a complete replacement for the code you've been using, it should **not** be used in tandem. Keep in mind that this does not have the fixed cover image import at the top, since I don't know your MyAnimeList username.

[Code](https://pastebin.com/raw/E9zLh1Y2)
![](https://i.imgur.com/qHWZFnY.png)

There are variables at the top of the code (--cover-width & --cover-height, primarily) that you can change to make the images a bit smaller/bigger if you want.

**Comment by VegethB** [comment]
> I think the code Shishio gave was more of a get-started kit than a polished modification to the theme.

Yes, yes. I did not specify well.
I meant (that having got a result like in his screenshot), most likely, the part after the comment referring to using Firefox to fix the theme was what I had to do (because that code was a startup-kit and not the final theme).



> Here's a preview image and the code. This is a complete replacement for the code you've been using, it should **not** be used in tandem. Keep in mind that this does not have the fixed cover image import at the top, since I don't know your MyAnimeList username.
> 
> [Code](https://pastebin.com/raw/E9zLh1Y2)
> ![](https://camo.githubusercontent.com/8a1c94363a96c33dd0bb4555d63bb39e907da900bfb25d141384c4a158d982e2/68747470733a2f2f692e696d6775722e636f6d2f7148575a466e592e706e67)
> 
> There are variables at the top of the code (--cover-width & --cover-height, primarily) that you can change to make the images a bit smaller/bigger if you want.

🔝👌 Thank you, it was already fine, with this I can already simplify some steps.
I had sketched this idea on firefox (before reading your comment now):
![image](https://user-images.githubusercontent.com/17975351/111785584-17894280-88bd-11eb-9273-4bd808ac486b.png)
and I was educating myself on how to apply it for all the posters.
