### ISSUE TITLE
Can't find how to add a banner.

### ISSUE THREAD

**Issue by saieeshb** [ValerioLyndon/MAL-Public-List-Designs#55]
Am I just really stupid? 

I can't find where to add the banner image on the brink theme for the last 45 mins. Please help me out and tell me where I add the url.  Much thanks.

**Comment by ValerioLyndon** [comment]
You can use the built-in uploader on MAL's style customization page, where you input the CSS. There are ways to use a URL, but it's not supported by default so some new code would need to be added.

![MAL settings](https://user-images.githubusercontent.com/29792052/121791730-dfcf2580-cba1-11eb-810a-6714b4d8b4f3.png)

There are ways to use a URL, but it's not supported by default so some new code would need to be added. Something like this should work, or the [per-category image mod](https://github.com/ValerioLyndon/MAL-Public-List-Designs/blob/6b8a9764298d5a5fa568c73adf4c3c64515ece69/Brink%20Theme/modPerCategoryImages.css) would work too. 

```
#cover-image-container {
	display: block !important;
}

#cover-image-container::before {
	content: "";
	display: block;
	width: 100%;
	max-width: initial;
	height: 30vw;
	min-height: calc(700px * 0.3);
	max-height: calc(1920px * 0.3);
	background: url(https://i.imgur.com/VNOplUb.jpg) center / cover;
}

/* Remove default image */
#cover-image {
	display: none;
}
```
