### ISSUE TITLE
[Brink] Black text in "Where to watch" popup

### ISSUE THREAD

**Issue by lawliet529** [ValerioLyndon/MAL-Public-List-Designs#72]
![Screenshot 2022-10-03 at 16-59-10 Lawliet529's Anime List - MyAnimeList net](https://user-images.githubusercontent.com/85656044/193557231-c8295287-569b-4875-abe5-9476d2f627f4.png)

I'm using newest code from master branch (Brink v1.8.1).
This happens on both Firefox and Chromium.

**Comment by ValerioLyndon** [comment]
Thank you very much for the bug report and fix once again, it's much appreciated!
