### ISSUE TITLE
[Brink] Gray-ish GDPR popup in MAL's dark mode

### ISSUE THREAD

**Issue by lawliet529** [ValerioLyndon/MAL-Public-List-Designs#77]
Since MAL implemented its own dark mode, the GDPR popup now looks like this with it enabled:

![out](https://github.com/ValerioLyndon/MAL-Public-List-Designs/assets/85656044/31ef15df-03e6-4bdf-a6ec-d5547acdc04f)

Fortunately, they also added a `dark-mode` class to the html document so this should be easy to fix.

```html
<html class="appearance-automatic dark-mode">
    ...
</html>
```

This `dark-mode` class only appears when MAL's theme is set to Dark or Automatic (browser must use dark mode).

**Comment by ValerioLyndon** [comment]
Thanks for pointing this out! I'll look into merging your PR after work tomorrow, and modifying the other themes as well.
