### ISSUE TITLE
[Help]: MAL Score + Statistics

### ISSUE THREAD

**Issue by GDjkhp** [ValerioLyndon/MAL-Public-List-Designs#80]
### Which theme are you using?

Clarity

### Describe your issue.

Update the themes to include MAL Score, would be cool with the new statistics.
![image](https://github.com/ValerioLyndon/MAL-Public-List-Designs/assets/51813377/d37ac542-b19a-416d-b5d4-58339d72ca24)

### What is your MyAnimeList username?

GDjkhp

### Your Custom CSS code.

```shell
N/A
```

### What browser(s) are you encountering the problem on?

Other

**Comment by ValerioLyndon** [comment]
I'm out of town for a week, so I unfortunately can't get to it yet, but it's on my to-do for the weekend!
